version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      # Group all production dependency updates into a single PR
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      # Group all dev dependency updates into a single PR
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      opentelemetry:
        patterns:
          - "@opentelemetry/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - ci
    groups:
      actions:
        patterns:
          - "*"
